# Generated by Django 3.1.7 on 2021-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('classroom', models.CharField(choices=[('X CG 1', 'X CG 1'), ('X PS 1', 'X PS 1'), ('X MM 1', 'X MM 1'), ('X TKJ 1', 'X TKJ 1'), ('X RPL 1', 'X RPL 1'), ('XI CG 1', 'XI CG 1'), ('XI PS 1', 'XI PS 1'), ('XI MM 1', 'XI MM 1'), ('XI TKJ 1', 'XI TKJ 1'), ('XI RPL 1', 'XI RPL 1'), ('XII CG 1', 'XII CG 1'), ('XII PS 1', 'XII PS 1'), ('XII MM 1', 'XII MM 1'), ('XII TKJ 1', 'XII TKJ 1'), ('XII RPL 1', 'XII RPL 1')], max_length=40, verbose_name='classroom')),
                ('question1', models.CharField(max_length=5000, verbose_name='1')),
                ('question2', models.CharField(max_length=5000, verbose_name='2')),
                ('question3', models.CharField(max_length=5000, verbose_name='3')),
                ('question4', models.CharField(max_length=5000, verbose_name='4')),
                ('question5', models.CharField(max_length=5000, verbose_name='5')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
